[package]
name = "KikoSwap"
version = "0.0.1"

[addresses]
KikoSwap = "0xa371dcd3556f40221b480bd1792c02ad"
StarcoinFramework = "0x1"

[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin-framework.git", rev="cf1deda"}
