[package]
name = "StarSwap"
version = "0.0.1"

[addresses]
StarSwap = "0x5ad03008d3c4d26c01a9c71225a3407a"
StarcoinFramework = "0x1"

[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin-framework.git", rev="cf1deda"}
