[package]
name = "StarSwap"
version = "0.0.1"

[addresses]
StarSwap = "0x8c109349c6bd91411d6bc962e080c4a3"
StarcoinFramework = "0x1"

[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin-framework.git", rev="cf1deda"}
